server:
  port: 8080

spring:
  application:
    name: la-vurger-api

  datasource:
    url: jdbc:postgresql://lavurguer-db.cxwmi8oy0i7m.eu-south-2.rds.amazonaws.com:5432/postgres
    username: postgres
    password: LaLoL!mpo1BL86
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
